In [1]:
import numpy as np

In [17]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.shape)
print(a.ndim)
print(a.itemsize)
print(a.dtype)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2
4
int32


In [20]:
a[1,-1]

8

In [21]:
a[0]

array([1, 2, 3, 4])

In [23]:
a[: ,2]

array([3, 7])

In [24]:
a[0,1]

2

In [25]:
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [30]:
a[1,-1:-4:-2] #range is exclusive =>[row,start_i:end_i:step]

array([8, 6])

In [31]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[1,2,3,4,5,6]])


In [41]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6]])

In [42]:
a[0,1]=43 #changing specific element

In [43]:
a

array([[ 1, 43,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6]])

In [44]:
a

array([[ 1, 43,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6]])

In [59]:
a[1:, 4]=2

In [60]:
a

array([[ 1, 43,  3,  4, 92,  6],
       [ 7,  8,  9, 10,  2, 12],
       [ 1,  2,  3,  4,  2,  6]])

In [61]:
a

array([[ 1, 43,  3,  4, 92,  6],
       [ 7,  8,  9, 10,  2, 12],
       [ 1,  2,  3,  4,  2,  6]])

In [62]:
a[:]

array([[ 1, 43,  3,  4, 92,  6],
       [ 7,  8,  9, 10,  2, 12],
       [ 1,  2,  3,  4,  2,  6]])

In [63]:
a[0:2]

array([[ 1, 43,  3,  4, 92,  6],
       [ 7,  8,  9, 10,  2, 12]])

In [64]:
a[0:2,1]

array([43,  8])

In [65]:
a[0:2,1:4] # ccessing specific rows, then specific colums

array([[43,  3,  4],
       [ 8,  9, 10]])

In [73]:
np.zeros(((2,3,2)))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [74]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [75]:
a

array([[ 1, 43,  3,  4, 92,  6],
       [ 7,  8,  9, 10,  2, 12],
       [ 1,  2,  3,  4,  2,  6]])

In [76]:
#passing direct values and not tuple to the random function
np.random.rand(3,3)  

array([[0.34347888, 0.66087512, 0.13110418],
       [0.80160685, 0.16260693, 0.03174919],
       [0.37801619, 0.23688135, 0.08082249]])

In [77]:
np.random.rand(3,2,2)

array([[[0.70940719, 0.60691722],
        [0.27843152, 0.20032893]],

       [[0.776569  , 0.25884582],
        [0.76723499, 0.56341411]],

       [[0.44521033, 0.26827672],
        [0.31309356, 0.43765066]]])

In [81]:
#randome integer ndarray ~different syntax from prev
np.random.randint(1,6, size=(2,2))

array([[5, 3],
       [1, 4]])

In [93]:
#constructing array by repeating elements 
b=np.array([[2,4,6]])
r=np.repeat(b,3,axis=0)
print(r)


[[2 4 6]
 [2 4 6]
 [2 4 6]]


In [95]:
output=np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [97]:
output[1:4,1:4]=np.zeros((3,3))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [99]:
output[2,2]=9
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [100]:
#making copies=>simply inistialising will point to same location
a=np.array([1,2,3])
b=a.copy()
b[0]=9
print(a)
print(b)


[1 2 3]
[9 2 3]


In [104]:
#data manipulation
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]


In [106]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[2,4,6],[8,10,12]])
print(b-a)

[[1 2 3]
 [4 5 6]]


In [107]:
print(a**2)

[[ 1  4  9]
 [16 25 36]]


In [108]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

Linear Algebra

In [109]:
#multiplication
a=np.ones((2,3))
b=np.full((3,2),3)
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]


In [110]:
np.matmul(a,b)

array([[9., 9.],
       [9., 9.]])

In [121]:
#find determinant
c=np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(c)
print(np.linalg.det(c))
print(np.linalg.matrix_rank(c))
print(np.linalg.inv(c))
print(np.linalg.matrix_power(c, 3))


[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
-306.0
3
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
[[336 162 228]
 [406 162 469]
 [698 702 905]]


STATISTICS

In [127]:
x=np.array([[1,2,3],[4,5,6]])
print(x)
#axis=1=> row wise min will be displayed
#axis=0=>col wise max printed
print(np.min(x, axis=1))
print(np.max(x,axis=0))
print(np.sum(x))
print(np.sum(x,axis=0)) #sum col wise
print(np.sum(x,axis=1)) #sum row-wise



[[1 2 3]
 [4 5 6]]
[1 4]
[4 5 6]
21
[5 7 9]
[ 6 15]


REORGANISING ARRAYS

In [130]:
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)
print(x.shape)
y=x.reshape((4,3))
print(y)




[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [133]:
x1=np.array([1,2,3,4])
x2=np.array([5,6,7,8])
#vertically stacking vectors
print(np.vstack([x1,x2]))
#horizontally stacking vectors
print(np.hstack([x1,x2]))

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
